### ISSUE TITLE
Add .codespellignore

### ISSUE THREAD

**Issue by ross-spencer** [ffdev-info/template.py#4]
Ignore words in pre-commit with a `.codespellignore` file, e.g. [here](https://github.com/exponential-decay/demystify/blob/main/.codespellignore)

Example config:

```
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.4
  hooks:
    - id: codespell
      args: [-I, .codespellignore]
```
