### ISSUE TITLE
.codespellignore

### ISSUE THREAD

**Issue by ross-spencer** [ffdev-info/template.py#9]
It's simply a preference to have a .codespellignore file for ignoring words as it's less prone to error, to add:

```yaml
  hooks:
    - id: codespell
      args: [-I, .codespellignore]
```

And add a pre-requisite `.codespellignore` file.
